{% set name = "vue" %}
{% set version = "2.5.13" %}
{% set sha256 = "8685737c408a2bba870e2fadf9649297d911a3cc73699278668ff4c09c5bd44c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vuejs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g vue
  requires:
    - nodejs
   

about:
  home: https://github.com/vuejs/vue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A progressive, incrementally-adoptable JavaScript framework for building UI on the web.'
  description: |
    Vue.js is an MIT-licensed open source project. It's an independent project 
    with its ongoing development made possible entirely thanks to the support 
    by these awesome backers.  
  doc_url: https://vuejs.org/
  dev_url: https://github.com/vuejs/vue

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
