{% set name = "vue" %}
{% set version = "2.6.3" %}
{% set sha256 = "ac9faccde8c057e78768a07ec5e2307dc07cfc47bfc104a2d578d7f067660871" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vuejs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g vue
  requires:
    - nodejs
   

about:
  home: https://github.com/vuejs/vue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A progressive, incrementally-adoptable JavaScript framework for building UI on the web.'
  description: |
    Vue.js is an MIT-licensed open source project. It's an independent project 
    with its ongoing development made possible entirely thanks to the support 
    by these awesome backers.  
  doc_url: https://vuejs.org/
  dev_url: https://github.com/vuejs/vue

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
