travis:
  secure:
    BINSTAR_TOKEN: UtbrHF/yIsq3OQCUj+NM28i1XDcCVRpmuLGu/BFt0R6//njUnVcTtz7bqri02dzXEs8GBTwZLp5EDHyUAqEHWCNfZkpAXh6JgPpHIJ7lc1pWe5qxoyPehpYQcF8KwUCVUjhnnyvOCKwZbJoVKtKPbOOa0GnwYg/Xt6gZ2jAXfx5zDfJ2jt27FC3nKcusJDoJ6wevgXRnqu4sxt+9XMTlA0hC+i+nSg3ojTi9UdN5eln9kyKABBzkYBjbI22+TQkcA25N8OhZYTxw2zjVe/zvUbbvD3Upu/AW22wYm+TKT0BWXLzp/FQ24AqOXNLw5z3QeGu/Zy2GX1Q2eyrDr8oyNmTkbKk5dHBMHUkFQ3vSHIwOPUk4FbfWHEVRX+iK4wl4GAdZbputBNlKV+j3BMX+TMN7eK/nvp2ywI6zL0Fu68WBmvcX4AKNooZXw1X/XciaNmMZ7X58WRrHacSHXnnYgRLtk+SIFnqHTCBcGPmyhElPSPAQRTTVumiYn/7DkQLPovcRc9VQm8vJN9+lgoBkEHH66ZKBTrlYgsAlIfRwCXYrGiaFoNrmmBEL1+x94r7Ehpq+IVPXhl4xBYG8VIQ7zIR9YsvRqcDEq15eFD66UTvqypAAQnAseUZpear5XrHe6kCMzTOvefMAhB4tRSw1ItqMteIp7MfSgJsOwlJGCxU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
