travis:
  secure:
    BINSTAR_TOKEN: ShLSeQuS4CJQvRLB1IFUgpkZMdwZqiRb+nmq/r87HEHoynvPuDwFdvKMFNWcE7RL0hJigwbpMxnXEL3HYpMzOI14tE1zY7XST5PiPMX+7eDhCdI49ZSrx94tspPfcjUqJ/+pNN3PAxjmpJbVlo5Sbw0pDiBcdFF/V3pOMUWLDJ0oAy8RMmAtyDar9g6i4ZV95LvJHkQr+v3Cy2yHAY8bbXB2sTxllzS3Ry05ebxUkpdDLz7N7siAflJ9/n5Ixzl9mn2drrDxnBAIdtpQ3jiurrDhLmk6eq9HMgYUXI/vKkbpTngMkfjtHcgbXQ94bDbS9UWQ9xauacRcHUicOf7Jl6NFd0vBizRwOxZKqyevZPpdS+a6gBllSDqjU65wB3BqUylKUOUT4DUaVICxjs1WZW2HCErHYDDgV4iEn6/UDphHlKYNYGtp0XmsqV8k+QTKwp22jUVab2IMrnfWVjJXG2Kewq/2cOGgPANncNtYBNr3PQ9qEAV1/o4nwcltrE5yv5zFlyOHKYvhAsrOuAWz1/rcUihhfyTjbSmT2mrVrIias/Vl+XYS0TCnr/qoTz5cJ2VYjyag/LL/9pAxcaMDtalXcu/05dxhDfHlGPcOcMGo8oDdME2W4WvVGb56Uc4a2P+2TL1u19TxYoBOvEsctYk8N6CY+djcbgaA4UVHzdY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
