travis:
  secure:
    BINSTAR_TOKEN: ukpDh4y/M0Ezjlqm3uHxHRlMb3o4v3N9dGTk7QHTrdni7DUzzIafGX78e19KeGpN91yrgVTOY4BuBcbGMMrdM/6IUVBfP9YH6aLnIX6X1HgLIT1061EDaVsREZjyqNPYia3zq2w4MUwIk5Y+mSZSTQ4VnMem1O9HLmWd3y0pJjk6e2v1uqvXN3tLvOpvkaFLY1tPbshNFDoBNQpKhbkeqa/l3bP+jsMTe+PZrz2sLMvEHVWuu/ZZ3J+Qzge2BF3JT1FDbj+gq72yB8XtJfAOCj3ZbA54IXIpIKC4fHfmnjhlfrteZT5f561WSFiLeSBd57IIEfJHk0CVEl2s5xwtNkRYt18QMldNiYlEeLLpmSSYe5sho+HuONeEo1JIo+uMPBFBGqZFwLCdHZYZc0F1kzQZKPpveoSsYGWdVeUNB3S0HSvCeW74I907ce/GnpRGvoCxU/3XJlF838Wr/Vc1xuX6cbK0DRu6o8N6XssAysRnBpgrOkuEIY0iacj2WeKoq5hPI4pJrDKcxQ+EugIMviAYm0P3uN4tq+RXlvQa9zzswNjREitAfKmh4d0mcQNpT/EZmB97XOSL+DZMFKZza339tI9d8NOAfyDtjK5iLTl01K0BOMj4t9KA1oLNKYx9jHpnSDOQiDpcE3GXVwSb/+H6ZMYo6o+FIlTR09k1W5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
